### PR TITLE
Remove `Shrinker` trait

### PR DESCRIPTION
**Pull request by apasel422**

### CODE REVIEW

**Comment by BurntSushi** [comment]
Oh my yes! I've been waiting for almost *a year* for this to be possible.

@apasel422 One nit: I like to follow `rustc`'s convention for breaking changes. Could you please put `[breaking-change]` in the commit message somewhere and briefly say what users have to do to update their code? Thanks!

**Comment by apasel422** [comment]
@BurntSushi I updated the commit message. Does that look OK to you?

**Comment by BurntSushi** [comment]
@apasel422 Poifect! Thank you!

**Comment by BurntSushi** [comment]
I've uploaded this fix to crates.io in `0.2.0`.

**Comment by BurntSushi** [comment]
(I accidentally uploaded this to `0.1.41`, but I've yanked that version.)

**Pull request merged**
