### PR TITLE
#[derive(Arbitrary)] V3

### PR DESCRIPTION
**Pull request by aelred**
I wanted to fix the last issue in #205 so I could learn how to debug and write Rust macros.

With this fix, I think the `#[derive(Arbitrary)]` feature is complete.

### CODE REVIEW

**Comment by aelred** [comment]
It looks like the tests are failing on 1.22.0 because [`lazy_static` 1.2.0 requires 1.24.1](https://github.com/rust-lang-nursery/lazy-static.rs/releases/tag/1.2.0) - that dependency comes very indirectly from `env_logger`.

I suppose the choices are either to bump the minimum version to 1.24.1, or fix the `env_logger` version to an earlier one that doesn't use `lazy_static` 1.2.0.

**Comment by maxbla** [comment]
@BurntSushi is this ready to merge?

**Comment by BurntSushi** [comment]
I have neither reviewed this nor even decided whether this is something that should be in quickcheck, so no, it is not ready to merge. Personally, this is something I'm unlikely to want to maintain, and I don't think it needs to live in this repo.

**Comment by BurntSushi** [comment]
I'm going to close this because I just don't have the bandwidth to maintain something like this at this time. I'd encourage folks willing to shoulder the maintenance to put this in a separate crate. Thanks!

**Pull request closed without merging**
