### PR TITLE
Implement Arbitrary for arrays

### LINKED ISSUE #92: Add Arbitrary implementation for small arrays
<strike>Alternatively implement `Arbitrary` for all arrays using the `FixedSizeArray` trait from the standard library (requires nightly).</strike> (see below).

### PR DESCRIPTION
**Pull request by kurnevsky**
It increases compilation time from ~3.5s to 13.5s in release mode on my laptop. Also not sure how long shrinking can take for [T; 32]. What do you think?

Fixes #92 #187

### CODE REVIEW

**Comment by BurntSushi** [comment]
I think my previous opinion hasn't really changed, and a ~4x hit to compile times seemingly confirms it.

**Comment by kurnevsky** [comment]
@BurntSushi I think it's essential to have this implementation to compete with proptest. If compilation time is so important we can have it behind a feature gate (added with the last commit).

**Comment by BurntSushi** [comment]
I don't agree. We don't need to "compete" with anyone. If proptest is better for arrays, then use proptest.

**Comment by BurntSushi** [comment]
We've made it this far without `Arbitrary` impls for arrays, we can wait a bit longer for const generics to land.

**Pull request closed without merging**
