### PR TITLE
Proper type annotation for modified prop function

### PR DESCRIPTION
**Pull request by badboy**

### CODE REVIEW

**Comment by gaborigloi** [comment]
I think the `Vec<int>`s should also be corrected in the README to `Vec<isize>`.

**Comment by badboy** [comment]
That's what you get for not testing the README :D 
Fixed it.

**Comment by gaborigloi** [comment]
Yeah, this is why I really like the idea of https://github.com/brson/rust-skeptic, which can test the  README :).

**Comment by BurntSushi** [comment]
Thanks!

**Pull request merged**
