### PR TITLE
Fix outdated integer suffixes

### PR DESCRIPTION
**Pull request by aepsil0n**

### CODE REVIEW

**Comment by BurntSushi** [comment]
Thanks!

**Comment by apasel422** [comment]
This issue was preventing quickcheck from building with the latest nightly. Could a new version be pushed to crates.io?

**Comment by BurntSushi** [comment]
I'm trying, but crates.io is not cooperating. (I think it's hosted on Github. :-/)

I'll keep trying.

**Comment by BurntSushi** [comment]
OK, `0.2.8` should be uploaded now.

**Pull request merged**
