### PR TITLE
Implement Arbitrary for 128-bit integers

### LINKED ISSUE #162: Implement `Arbitrary` for 128-bit integers
`rand` supports it now, so, we can support it here too.

### PR DESCRIPTION
**Pull request by tokenrove**
Now that rust-lang-nursery/rand#163 is merged we can do this.

Closes #162.

### CODE REVIEW

**Comment by tokenrove** [comment]
Urk.  I was a little quick on the draw there.  Sorry, let me clean this up.

**Comment by tokenrove** [comment]
`rand` has been released and this builds now.  Let me know if there's anything else I should do.  Thanks.

**Comment by tokenrove** [comment]
Oops.  Some leftover from fiddling with features.  Should be clean now.  Thanks.

**Comment by BurntSushi** [comment]
`quickcheck 0.5.1` is on crates.io with this change. Thanks again!

**Comment by BurntSushi** [comment]
I goofed. `rand` is a public dep, so I actually needed to do a major version bump. I yanked `0.5.1` and released `0.6.0`.

**Pull request merged**
