### PR TITLE
Update rand to version 0.4

### PR DESCRIPTION
**Pull request by debris**
Just a version bump

Can you release new version of quickcheck to crates.io?

### CODE REVIEW

**Comment by debris** [comment]
fail on nightly is unrelated

**Comment by BurntSushi** [comment]
Thanks! I'm going to wait to get the nightly fix in before making a release.

**Comment by BurntSushi** [comment]
`quickcheck 0.5.1` is on crates.io with this change. Thanks again!

**Comment by BurntSushi** [comment]
I goofed. `rand` is a public dep, so I actually needed to do a major version bump. I yanked `0.5.1` and released `0.6.0`.

**Pull request merged**
